setwd("Documents/corpus_annotation_tp/R_files/")
load(".RData")
load("c2_long.RData")
source("functions_corpus_tp.R")
library(ggplot2)
library("stringr")
library(tidyr)
plot_percentages(c2_long)
load("c1_long.RData")
load("c2_long.RData")

plot_percentages(c1_long)
View(feats_in_units)
load("b2_long.RData")
plot_percentages(b2_long)
feats_level <- get_feats_in_levels_df(all_features, "../testing/")
level_counts <- count_texts_per_level("../data/")
